spring:
  dubbo:
    application:
      name: fund
      environment: test
    registry:
      protocol: zookeeper
      address: 127.0.0.1
      port: 2181
      register: true
    protocol:
      name: dubbo
      port: 9091
    consumer:
      timeout: 6000