server:
  port: 8080
spring:
  datasource:
    dbcp2:
      username: root
      password: root
      url: jdbc:mysql://192.168.0.115:3306/test_db?useUnicode=true&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      max-total: 100
      max-wait-millis: 1000
      min-idle: 10
      initial-size: 10
  memcached:
    servers: 127.0.0.1:11211
    weights: 1
    connectionPoolSize:
    commandFactory: BINARY
    sessionLocator: KETAMA
    failureMode: false
  dubbo:
    application:
      name: fund
      environment: test
    registry:
      protocol: zookeeper
      address: 127.0.0.1
      port: 2181
      register: true
    protocol:
      name: dubbo
      port: 9091
    consumer:
      timeout: 6000
  redis:
    database: 0
    host: 192.168.0.115
    port: 6379
    pool:
      max-active: 10
      max-idle: 8
      max-wait: -1
      min-idle: 0
    timeout: 0