server:
  port: 8080
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.0.107:3306/testdb?autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      initial-size: 10
      max-idle: 20
      max-total: 100
      min-idle: 10

