spring:
  dubbo:
    application:
      name: fund
      environment: test
    registry:
      protocol: zookeeper
      address: 192.168.0.115
      port: 2181
      register: true
    protocol:
      name: dubbo
      port: 9090
    consumer:
      timeout: 6000

